import { useState } from "react";
import { 
  Accordion, 
  AccordionContent, 
  AccordionItem, 
  AccordionTrigger 
} from "@/components/ui/accordion";

export default function FaqSection() {
  const faqs = [
    {
      id: 1,
      question: "Is WebCraft AI really free?",
      answer: "Yes, WebCraft AI is completely free to use without any paid subscription model. You can create and download as many websites as you need at no cost."
    },
    {
      id: 2,
      question: "Do I need coding knowledge to use this tool?",
      answer: "Not at all! WebCraft AI is designed for everyone, regardless of technical knowledge. Just describe what you want in plain language, and our AI will handle the rest."
    },
    {
      id: 3,
      question: "How do I publish my website after downloading?",
      answer: "After downloading your website files, you can upload them to any web hosting service. We have guides for popular hosting providers like GitHub Pages, Netlify, and Vercel in our help section."
    },
    {
      id: 4,
      question: "Can I edit my website after it's generated?",
      answer: "Yes! The downloaded website includes clean, well-organized HTML, CSS, and JavaScript files that you can edit with any code editor. Or you can use our tool to regenerate with a modified prompt."
    },
    {
      id: 5,
      question: "Are the websites mobile-friendly?",
      answer: "Absolutely! All websites generated by WebCraft AI are fully responsive and look great on all devices - desktops, tablets, and mobile phones."
    }
  ];

  return (
    <section className="py-16 px-4 bg-white">
      <div className="max-w-3xl mx-auto">
        <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-900 mb-12">
          Frequently Asked Questions
        </h2>
        
        <div>
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq) => (
              <AccordionItem 
                key={faq.id} 
                value={`item-${faq.id}`}
                className="border border-gray-200 rounded-lg overflow-hidden"
              >
                <AccordionTrigger className="px-4 py-4 bg-white hover:bg-gray-50 transition-colors">
                  <span className="font-medium text-gray-900">{faq.question}</span>
                </AccordionTrigger>
                <AccordionContent className="px-4 bg-white border-t border-gray-100">
                  <p className="text-gray-600">{faq.answer}</p>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
